{{- if .Values.restic.createSecret }}
---
apiVersion: v1
data:
{{- if eq .Values.restic.repositoryType "s3" }}
  AWS_ACCESS_KEY_ID: {{ .Values.restic.s3.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.restic.s3.secretKey | b64enc }}
{{- else if eq .Values.restic.repositoryType "sftp" }}
  config: {{ .Values.restic.sftp.config | b64enc }}
  id_rsa: {{ .Values.restic.sftp.id_rsa | b64enc }}
{{- else }}
{{ fail "Invalid restic.repositoryType set, must be s3 or sftp!" }}
{{- end }}
kind: Secret
metadata:
  name: {{ include "restics3bucketbackup.fullname" . }}-credentials
  labels:
    {{- include "restics3bucketbackup.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.restic.password }}
---
apiVersion: v1
data:
  RESTIC_PASSWORD: {{ .Values.restic.password | b64enc }}
kind: Secret
metadata:
  name: {{ include "restics3bucketbackup.fullname" . }}-repository
  labels:
    {{- include "restics3bucketbackup.labels" . | nindent 4 }}
{{- end }}
