---
apiVersion: v1
data:
{{- if .Values.s3fs.accessKey }}
  S3FS_AWS_ACCESS_KEY_ID: {{ .Values.s3fs.accessKey | b64enc }}
{{- end }}
{{- if .Values.s3fs.secretKey }}
  S3FS_AWS_SECRET_ACCESS_KEY: {{ .Values.s3fs.secretKey | b64enc }}
{{- end }}
{{- if .Values.s3fs.flags }}
  S3FS_FLAGS: {{ .Values.s3fs.flags | b64enc }}
{{- end }}
{{- if .Values.s3fs.bucketName }}
  BUCKET_NAME: {{ .Values.s3fs.bucketName | b64enc }}
{{- end }}
{{- if eq .Values.restic.repositoryType "s3" }}
{{- if .Values.restic.s3.accessKey }}
  AWS_ACCESS_KEY_ID: {{ .Values.restic.s3.accessKey | b64enc }}
{{- end }}
{{- if .Values.restic.s3.secretKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.restic.s3.secretKey | b64enc }}
{{- end }}
{{- else if eq .Values.restic.repositoryType "sftp" }}
  config: {{ .Values.restic.sftp.config | b64enc }}
  id_rsa: {{ .Values.restic.sftp.id_rsa | b64enc }}
{{- else }}
{{ fail "Invalid restic.repositoryType set, must be s3 or sftp!" }}
{{- end }}
kind: Secret
metadata:
  name: {{ include "restics3bucketbackup.fullname" . }}-credentials
  labels:
    {{- include "restics3bucketbackup.labels" . | nindent 4 }}
{{- if or .Values.restic.repository .Values.restic.password }}
---
apiVersion: v1
data:
  {{- if .Values.restic.repository }}
  RESTIC_REPOSITORY: {{ .Values.restic.repository | b64enc }}
  {{- end }}
  {{- if .Values.restic.password }}
  RESTIC_PASSWORD: {{ .Values.restic.password | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: {{ include "restics3bucketbackup.fullname" . }}-repository
  labels:
    {{- include "restics3bucketbackup.labels" . | nindent 4 }}
{{- end }}
