apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    {{- include "zalando-postgresql.labels" . | nindent 4 }}
  name: {{ include "zalando-postgresql.name" . }}
spec:
  {{- toYaml .Values.spec | nindent 2 }}
